2023-02-23 19:36:34 [   DEBUG] (conftest.py:49) Using XerxesNetwork(port=Serial(port='/dev/ttyUSB0',baudrate=115200, timeout=0.01))
2023-02-23 19:36:34 [   DEBUG] (conftest.py:64) Using XerxesRoot(my_addr=Addr(0x1e), network=XerxesNetwork(port=Serial(port='/dev/ttyUSB0',baudrate=115200, timeout=0.01)))
2023-02-23 19:36:34 [   DEBUG] (leaf.py:314) Unlocking memory for hard reset
2023-02-23 19:36:34 [   DEBUG] (leaf.py:189) Writing memory element:memory_lock at address:384, type:I, value:1437226410.
2023-02-23 19:36:34 [   DEBUG] (leaf.py:296) Write successful.
2023-02-23 19:36:34 [   DEBUG] (leaf.py:316) Memory unlocked, resetting leaf to factory settings.
2023-02-23 19:36:35 [   DEBUG] (conftest.py:112) Leaf ping: XerxesPingReply(dev_id=DevId(0x22), v_maj=1, v_min=4, latency=0.006490851999842562)
2023-02-23 19:36:35 [   DEBUG] (leaf.py:162) Reading memory element:device_config at address:40, type:B.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:171) Read value: 0
2023-02-23 19:36:35 [   DEBUG] (leaf.py:189) Writing memory element:device_config at address:40, type:B, value:1.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:296) Write successful.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:162) Reading memory element:device_config at address:40, type:B.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:171) Read value: 1
2023-02-23 19:36:35 [   DEBUG] (leaf.py:162) Reading memory element:net_cycle_time_us at address:544, type:I.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:171) Read value: 695
2023-02-23 19:36:35 [   DEBUG] (test_sensor_overload.py:36) Cycle time is 695 us
2023-02-23 19:36:35 [   DEBUG] (test_sensor_overload.py:43) Setting cycle time to 0 us
2023-02-23 19:36:35 [   DEBUG] (leaf.py:189) Writing memory element:desired_cycle_time_us at address:32, type:I, value:0.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:296) Write successful.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:162) Reading memory element:device_error at address:520, type:Q.
2023-02-23 19:36:35 [   DEBUG] (leaf.py:171) Read value: 24
2023-02-23 19:36:35 [   DEBUG] (test_sensor_overload.py:53) Errors: 24
